---
- name: pycapi setup
  hosts: vps
  become: yes
  vars:
    repo_url: "https://github.com/foxxytux/pycapi.git"

  tasks:
    - name: Install system dependencies
      apt:
        name: [curl, python3-pip, python3-kubernetes]
        update_cache: yes
        state: present

    - name: Install K3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Create ArgoCD Namespace
      kubernetes.core.k8s:
        name: argocd
        kind: Namespace
        state: present

    - name: Install ArgoCD
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        namespace: argocd

    - name: Wait for ArgoCD Server to be ready
      kubernetes.core.k8s_info:
        kind: Deployment
        name: argocd-server
        namespace: argocd
      register: argo_status
      until: argo_status.resources[0].status.readyReplicas | default(0) > 0
      retries: 30
      delay: 10

    - name: Setup the pycapi Automatic Application
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: pycapi-app
            namespace: argocd
          spec:
            project: default
            source:
              repoURL: "{{ repo_url }}"
              targetRevision: HEAD
              path: .
            destination:
              server: https://kubernetes.default.svc
              namespace: default
            syncPolicy:
              automated:
                prune: true
                selfHeal: true

    - name: Expose ArgoCD UI (NodePort)
      kubernetes.core.k8s:
        state: patched
        kind: Service
        name: argocd-server
        namespace: argocd
        definition:
          spec:
            type: NodePort
